<?php

namespace Wordfence\WPKit;

class ExitCodes
{
	const EXIT_CODE_INFORMATIONAL_ONLY = 0;
	const EXIT_CODE_EXPLOIT_SUCCEEDED = 1;
	const EXIT_CODE_EXPLOIT_FAILED = 2;
	const EXIT_CODE_FAILED_PRECONDITION = 3;
	const EXIT_CODE_VALID_REQUEST_FAILED = 4;
}